# Generated by Django 3.0.2 on 2020-10-06 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20201006_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Customer'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Out for delivery'), ('3', 'Delivered'), ('4', 'Cancelled')], max_length=200, null=True),
        ),
    ]
