# Generated by Django 3.1.2 on 2020-10-22 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.title'),
        ),
    ]
